import os
import re
import sys
INCLUDE_PATTERN = re.compile(r'^\s*#include\s+"([^"]+)"')
def find_file(filename, search_paths):
    for path in search_paths:
        full_path = os.path.join(path, filename)
        if os.path.exists(full_path):
            return full_path
    return None
def process_file(input_path, output_file, processed_files=None, depth=0):
    if processed_files is None:
        processed_files = set()
    base_dir = os.path.dirname(input_path)
    indent = "  " * depth
    print(f"{indent}-> Processing: {input_path}")
    try:
        with open(input_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
    except Exception as e:
        print(f"Error reading file {input_path}: {e}")
        output_file.write(f"; ERROR: Could not read included file: {input_path}\n")
        return
    for line in lines:
        match = INCLUDE_PATTERN.match(line)
        if match:
            included_filename = match.group(1)
            found_path = find_file(included_filename, [base_dir, os.getcwd()])
            if found_path:
                output_file.write(f"\n; >>> BEGIN EXPANSION: {included_filename} <<<\n")
                process_file(found_path, output_file, processed_files, depth + 1)
                output_file.write(f"; <<< END EXPANSION: {included_filename} >>>\n\n")
            else:
                print(f"Warning: Could not find included file '{included_filename}' referenced in '{input_path}'")
                output_file.write(f"; Warning: File not found locally, keeping original include\n")
                output_file.write(line)
        else:
            output_file.write(line)
def run_expansion(input_top_path, output_top_path):
    if not os.path.exists(input_top_path):
        return False, f"File not found: {input_top_path}"
    try:
        with open(output_top_path, 'w', encoding='utf-8') as out_f:
            out_f.write(f"; Generated by GROMACS Tool\n")
            out_f.write(f"; Original file: {input_top_path}\n\n")
            abs_input_path = os.path.abspath(input_top_path)
            process_file(abs_input_path, out_f)
        return True, f"Success! File processed"
    except Exception as e:
        return False, f"Error occurred: {str(e)}"
