# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 741)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Bonds_Angles = QtWidgets.QWidget()
        self.Bonds_Angles.setObjectName("Bonds_Angles")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Bonds_Angles)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_project = QtWidgets.QGroupBox(self.Bonds_Angles)
        self.groupBox_project.setObjectName("groupBox_project")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_project)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_project_name = QtWidgets.QLabel(self.groupBox_project)
        self.label_project_name.setObjectName("label_project_name")
        self.gridLayout_2.addWidget(self.label_project_name, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_project_name = QtWidgets.QLineEdit(self.groupBox_project)
        self.lineEdit_project_name.setObjectName("lineEdit_project_name")
        self.gridLayout_2.addWidget(self.lineEdit_project_name, 0, 1, 1, 1)
        self.pushButton_project_folder = QtWidgets.QPushButton(self.groupBox_project)
        self.pushButton_project_folder.setObjectName("pushButton_project_folder")
        self.gridLayout_2.addWidget(self.pushButton_project_folder, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_project_folder = QtWidgets.QLineEdit(self.groupBox_project)
        self.lineEdit_project_folder.setObjectName("lineEdit_project_folder")
        self.gridLayout_2.addWidget(self.lineEdit_project_folder, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.pushButton_create_folder = QtWidgets.QPushButton(self.groupBox_project)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_create_folder.sizePolicy().hasHeightForWidth())
        self.pushButton_create_folder.setSizePolicy(sizePolicy)
        self.pushButton_create_folder.setObjectName("pushButton_create_folder")
        self.horizontalLayout_2.addWidget(self.pushButton_create_folder)
        self.verticalLayout_2.addWidget(self.groupBox_project)
        self.groupBox_input = QtWidgets.QGroupBox(self.Bonds_Angles)
        self.groupBox_input.setObjectName("groupBox_input")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_input)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_topology_file = QtWidgets.QLabel(self.groupBox_input)
        self.label_topology_file.setObjectName("label_topology_file")
        self.gridLayout_3.addWidget(self.label_topology_file, 0, 0, 1, 1)
        self.browse_coodrinate = QtWidgets.QPushButton(self.groupBox_input)
        self.browse_coodrinate.setObjectName("browse_coodrinate")
        self.gridLayout_3.addWidget(self.browse_coodrinate, 1, 2, 1, 1)
        self.label_coordinate_file = QtWidgets.QLabel(self.groupBox_input)
        self.label_coordinate_file.setObjectName("label_coordinate_file")
        self.gridLayout_3.addWidget(self.label_coordinate_file, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_topology_file = QtWidgets.QLineEdit(self.groupBox_input)
        self.lineEdit_topology_file.setObjectName("lineEdit_topology_file")
        self.gridLayout_3.addWidget(self.lineEdit_topology_file, 0, 1, 1, 1)
        self.browse_topology_browse = QtWidgets.QPushButton(self.groupBox_input)
        self.browse_topology_browse.setObjectName("browse_topology_browse")
        self.gridLayout_3.addWidget(self.browse_topology_browse, 0, 2, 1, 1)
        self.coordinate_file_Edit = QtWidgets.QLineEdit(self.groupBox_input)
        self.coordinate_file_Edit.setObjectName("coordinate_file_Edit")
        self.gridLayout_3.addWidget(self.coordinate_file_Edit, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.pushButton_process_input = QtWidgets.QPushButton(self.groupBox_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_process_input.sizePolicy().hasHeightForWidth())
        self.pushButton_process_input.setSizePolicy(sizePolicy)
        self.pushButton_process_input.setObjectName("pushButton_process_input")
        self.horizontalLayout.addWidget(self.pushButton_process_input)
        self.verticalLayout_2.addWidget(self.groupBox_input)
        self.create_vdata_groupbox = QtWidgets.QGroupBox(self.Bonds_Angles)
        self.create_vdata_groupbox.setObjectName("create_vdata_groupbox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.create_vdata_groupbox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_Multiplicity = QtWidgets.QLabel(self.create_vdata_groupbox)
        self.label_Multiplicity.setObjectName("label_Multiplicity")
        self.gridLayout_4.addWidget(self.label_Multiplicity, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_charge = QtWidgets.QLabel(self.create_vdata_groupbox)
        self.label_charge.setObjectName("label_charge")
        self.gridLayout_4.addWidget(self.label_charge, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_Multiplicity = QtWidgets.QLineEdit(self.create_vdata_groupbox)
        self.lineEdit_Multiplicity.setObjectName("lineEdit_Multiplicity")
        self.gridLayout_4.addWidget(self.lineEdit_Multiplicity, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_charge = QtWidgets.QLineEdit(self.create_vdata_groupbox)
        self.lineEdit_charge.setObjectName("lineEdit_charge")
        self.gridLayout_4.addWidget(self.lineEdit_charge, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.method_label = QtWidgets.QLabel(self.create_vdata_groupbox)
        self.method_label.setObjectName("method_label")
        self.gridLayout_4.addWidget(self.method_label, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.comboBox_method = QtWidgets.QComboBox(self.create_vdata_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_method.sizePolicy().hasHeightForWidth())
        self.comboBox_method.setSizePolicy(sizePolicy)
        self.comboBox_method.setMinimumSize(QtCore.QSize(110, 0))
        self.comboBox_method.setEditable(False)
        self.comboBox_method.setObjectName("comboBox_method")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_method, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.basis_label = QtWidgets.QLabel(self.create_vdata_groupbox)
        self.basis_label.setObjectName("basis_label")
        self.gridLayout_4.addWidget(self.basis_label, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.comboBox_basis = QtWidgets.QComboBox(self.create_vdata_groupbox)
        self.comboBox_basis.setObjectName("comboBox_basis")
        self.comboBox_basis.addItem("")
        self.comboBox_basis.addItem("")
        self.comboBox_basis.addItem("")
        self.comboBox_basis.addItem("")
        self.comboBox_basis.addItem("")
        self.comboBox_basis.addItem("")
        self.comboBox_basis.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_basis, 1, 3, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_4)
        self.compute_button = QtWidgets.QPushButton(self.create_vdata_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compute_button.sizePolicy().hasHeightForWidth())
        self.compute_button.setSizePolicy(sizePolicy)
        self.compute_button.setMinimumSize(QtCore.QSize(20, 0))
        self.compute_button.setMaximumSize(QtCore.QSize(83, 16777215))
        self.compute_button.setObjectName("compute_button")
        self.horizontalLayout_3.addWidget(self.compute_button)
        self.verticalLayout_2.addWidget(self.create_vdata_groupbox)
        self.groupBox_select_atoms = QtWidgets.QGroupBox(self.Bonds_Angles)
        self.groupBox_select_atoms.setObjectName("groupBox_select_atoms")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_select_atoms)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_angles = QtWidgets.QLabel(self.groupBox_select_atoms)
        self.label_angles.setObjectName("label_angles")
        self.gridLayout_5.addWidget(self.label_angles, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_angles = QtWidgets.QLineEdit(self.groupBox_select_atoms)
        self.lineEdit_angles.setObjectName("lineEdit_angles")
        self.gridLayout_5.addWidget(self.lineEdit_angles, 1, 1, 1, 1)
        self.label_bonds = QtWidgets.QLabel(self.groupBox_select_atoms)
        self.label_bonds.setObjectName("label_bonds")
        self.gridLayout_5.addWidget(self.label_bonds, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_bonds = QtWidgets.QLineEdit(self.groupBox_select_atoms)
        self.lineEdit_bonds.setObjectName("lineEdit_bonds")
        self.gridLayout_5.addWidget(self.lineEdit_bonds, 0, 1, 1, 1)
        self.label_removed_frequency = QtWidgets.QLabel(self.groupBox_select_atoms)
        self.label_removed_frequency.setObjectName("label_removed_frequency")
        self.gridLayout_5.addWidget(self.label_removed_frequency, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_remove_frequency = QtWidgets.QLineEdit(self.groupBox_select_atoms)
        self.lineEdit_remove_frequency.setObjectName("lineEdit_remove_frequency")
        self.gridLayout_5.addWidget(self.lineEdit_remove_frequency, 2, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_select_all = QtWidgets.QCheckBox(self.groupBox_select_atoms)
        self.checkBox_select_all.setObjectName("checkBox_select_all")
        self.verticalLayout.addWidget(self.checkBox_select_all)
        self.pushButton_view_vibration = QtWidgets.QPushButton(self.groupBox_select_atoms)
        self.pushButton_view_vibration.setObjectName("pushButton_view_vibration")
        self.verticalLayout.addWidget(self.pushButton_view_vibration)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.groupBox_select_atoms)
        self.target_setting_groupbox = QtWidgets.QGroupBox(self.Bonds_Angles)
        self.target_setting_groupbox.setObjectName("target_setting_groupbox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.target_setting_groupbox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.wavenumber_tol_label = QtWidgets.QLabel(self.target_setting_groupbox)
        self.wavenumber_tol_label.setObjectName("wavenumber_tol_label")
        self.gridLayout.addWidget(self.wavenumber_tol_label, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_weight = QtWidgets.QLineEdit(self.target_setting_groupbox)
        self.lineEdit_weight.setObjectName("lineEdit_weight")
        self.gridLayout.addWidget(self.lineEdit_weight, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.cm1_label = QtWidgets.QLabel(self.target_setting_groupbox)
        self.cm1_label.setObjectName("cm1_label")
        self.gridLayout.addWidget(self.cm1_label, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.browse_user_vdata = QtWidgets.QPushButton(self.target_setting_groupbox)
        self.browse_user_vdata.setObjectName("browse_user_vdata")
        self.gridLayout.addWidget(self.browse_user_vdata, 1, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_wavenumber = QtWidgets.QLineEdit(self.target_setting_groupbox)
        self.lineEdit_wavenumber.setObjectName("lineEdit_wavenumber")
        self.gridLayout.addWidget(self.lineEdit_wavenumber, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.user_vdata_label = QtWidgets.QLabel(self.target_setting_groupbox)
        self.user_vdata_label.setObjectName("user_vdata_label")
        self.gridLayout.addWidget(self.user_vdata_label, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.weight_label = QtWidgets.QLabel(self.target_setting_groupbox)
        self.weight_label.setObjectName("weight_label")
        self.gridLayout.addWidget(self.weight_label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.comboBox_reassign_modes = QtWidgets.QComboBox(self.target_setting_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_reassign_modes.sizePolicy().hasHeightForWidth())
        self.comboBox_reassign_modes.setSizePolicy(sizePolicy)
        self.comboBox_reassign_modes.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_reassign_modes.setObjectName("comboBox_reassign_modes")
        self.comboBox_reassign_modes.addItem("")
        self.comboBox_reassign_modes.addItem("")
        self.gridLayout.addWidget(self.comboBox_reassign_modes, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_user_vdata = QtWidgets.QLineEdit(self.target_setting_groupbox)
        self.lineEdit_user_vdata.setObjectName("lineEdit_user_vdata")
        self.gridLayout.addWidget(self.lineEdit_user_vdata, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_reassigan_mode = QtWidgets.QLabel(self.target_setting_groupbox)
        self.label_reassigan_mode.setObjectName("label_reassigan_mode")
        self.gridLayout.addWidget(self.label_reassigan_mode, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.target_setting_groupbox)
        self.run_button = QtWidgets.QPushButton(self.Bonds_Angles)
        self.run_button.setObjectName("run_button")
        self.verticalLayout_2.addWidget(self.run_button)
        self.tabWidget.addTab(self.Bonds_Angles, "")
        self.Dihedral = QtWidgets.QWidget()
        self.Dihedral.setObjectName("Dihedral")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Dihedral)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_project_2 = QtWidgets.QGroupBox(self.Dihedral)
        self.groupBox_project_2.setObjectName("groupBox_project_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_project_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_project_name_2 = QtWidgets.QLabel(self.groupBox_project_2)
        self.label_project_name_2.setObjectName("label_project_name_2")
        self.gridLayout_7.addWidget(self.label_project_name_2, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_project_name_2 = QtWidgets.QLineEdit(self.groupBox_project_2)
        self.lineEdit_project_name_2.setObjectName("lineEdit_project_name_2")
        self.gridLayout_7.addWidget(self.lineEdit_project_name_2, 0, 1, 1, 1)
        self.pushButton_project_folder_2 = QtWidgets.QPushButton(self.groupBox_project_2)
        self.pushButton_project_folder_2.setObjectName("pushButton_project_folder_2")
        self.gridLayout_7.addWidget(self.pushButton_project_folder_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_project_folder_2 = QtWidgets.QLineEdit(self.groupBox_project_2)
        self.lineEdit_project_folder_2.setObjectName("lineEdit_project_folder_2")
        self.gridLayout_7.addWidget(self.lineEdit_project_folder_2, 1, 1, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_7)
        self.pushButton_create_folder_2 = QtWidgets.QPushButton(self.groupBox_project_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_create_folder_2.sizePolicy().hasHeightForWidth())
        self.pushButton_create_folder_2.setSizePolicy(sizePolicy)
        self.pushButton_create_folder_2.setObjectName("pushButton_create_folder_2")
        self.horizontalLayout_8.addWidget(self.pushButton_create_folder_2)
        self.verticalLayout_4.addWidget(self.groupBox_project_2)
        self.groupBox_input_2 = QtWidgets.QGroupBox(self.Dihedral)
        self.groupBox_input_2.setObjectName("groupBox_input_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_input_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_topology_file_2 = QtWidgets.QLabel(self.groupBox_input_2)
        self.label_topology_file_2.setObjectName("label_topology_file_2")
        self.gridLayout_6.addWidget(self.label_topology_file_2, 0, 0, 1, 1)
        self.browse_coodrinate_2 = QtWidgets.QPushButton(self.groupBox_input_2)
        self.browse_coodrinate_2.setObjectName("browse_coodrinate_2")
        self.gridLayout_6.addWidget(self.browse_coodrinate_2, 1, 2, 1, 1)
        self.label_coordinate_file_2 = QtWidgets.QLabel(self.groupBox_input_2)
        self.label_coordinate_file_2.setObjectName("label_coordinate_file_2")
        self.gridLayout_6.addWidget(self.label_coordinate_file_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_topology_file_2 = QtWidgets.QLineEdit(self.groupBox_input_2)
        self.lineEdit_topology_file_2.setObjectName("lineEdit_topology_file_2")
        self.gridLayout_6.addWidget(self.lineEdit_topology_file_2, 0, 1, 1, 1)
        self.browse_topology_browse_2 = QtWidgets.QPushButton(self.groupBox_input_2)
        self.browse_topology_browse_2.setObjectName("browse_topology_browse_2")
        self.gridLayout_6.addWidget(self.browse_topology_browse_2, 0, 2, 1, 1)
        self.coordinate_file_Edit_2 = QtWidgets.QLineEdit(self.groupBox_input_2)
        self.coordinate_file_Edit_2.setObjectName("coordinate_file_Edit_2")
        self.gridLayout_6.addWidget(self.coordinate_file_Edit_2, 1, 1, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_6)
        self.pushButton_process_input_2 = QtWidgets.QPushButton(self.groupBox_input_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_process_input_2.sizePolicy().hasHeightForWidth())
        self.pushButton_process_input_2.setSizePolicy(sizePolicy)
        self.pushButton_process_input_2.setObjectName("pushButton_process_input_2")
        self.horizontalLayout_7.addWidget(self.pushButton_process_input_2)
        self.verticalLayout_4.addWidget(self.groupBox_input_2)
        self.groupBox_select_atoms_2 = QtWidgets.QGroupBox(self.Dihedral)
        self.groupBox_select_atoms_2.setObjectName("groupBox_select_atoms_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_select_atoms_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_dihedral_angle = QtWidgets.QLabel(self.groupBox_select_atoms_2)
        self.label_dihedral_angle.setObjectName("label_dihedral_angle")
        self.horizontalLayout_9.addWidget(self.label_dihedral_angle)
        self.lineEdit_select_dihedral_angle = QtWidgets.QLineEdit(self.groupBox_select_atoms_2)
        self.lineEdit_select_dihedral_angle.setObjectName("lineEdit_select_dihedral_angle")
        self.horizontalLayout_9.addWidget(self.lineEdit_select_dihedral_angle)
        self.pushButton_view_dihedral = QtWidgets.QPushButton(self.groupBox_select_atoms_2)
        self.pushButton_view_dihedral.setEnabled(True)
        self.pushButton_view_dihedral.setObjectName("pushButton_view_dihedral")
        self.horizontalLayout_9.addWidget(self.pushButton_view_dihedral)
        self.verticalLayout_4.addWidget(self.groupBox_select_atoms_2)
        self.create_vdata_groupbox_2 = QtWidgets.QGroupBox(self.Dihedral)
        self.create_vdata_groupbox_2.setObjectName("create_vdata_groupbox_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.create_vdata_groupbox_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit_charge_2 = QtWidgets.QLineEdit(self.create_vdata_groupbox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_charge_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_charge_2.setSizePolicy(sizePolicy)
        self.lineEdit_charge_2.setObjectName("lineEdit_charge_2")
        self.gridLayout_8.addWidget(self.lineEdit_charge_2, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_Multiplicity_2 = QtWidgets.QLineEdit(self.create_vdata_groupbox_2)
        self.lineEdit_Multiplicity_2.setObjectName("lineEdit_Multiplicity_2")
        self.gridLayout_8.addWidget(self.lineEdit_Multiplicity_2, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.comboBox_method_2 = QtWidgets.QComboBox(self.create_vdata_groupbox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_method_2.sizePolicy().hasHeightForWidth())
        self.comboBox_method_2.setSizePolicy(sizePolicy)
        self.comboBox_method_2.setMinimumSize(QtCore.QSize(110, 0))
        self.comboBox_method_2.setEditable(False)
        self.comboBox_method_2.setObjectName("comboBox_method_2")
        self.comboBox_method_2.addItem("")
        self.comboBox_method_2.addItem("")
        self.comboBox_method_2.addItem("")
        self.comboBox_method_2.addItem("")
        self.comboBox_method_2.addItem("")
        self.comboBox_method_2.addItem("")
        self.comboBox_method_2.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_method_2, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.basis_label_2 = QtWidgets.QLabel(self.create_vdata_groupbox_2)
        self.basis_label_2.setObjectName("basis_label_2")
        self.gridLayout_8.addWidget(self.basis_label_2, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.method_label_2 = QtWidgets.QLabel(self.create_vdata_groupbox_2)
        self.method_label_2.setObjectName("method_label_2")
        self.gridLayout_8.addWidget(self.method_label_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_Multiplicity_2 = QtWidgets.QLabel(self.create_vdata_groupbox_2)
        self.label_Multiplicity_2.setObjectName("label_Multiplicity_2")
        self.gridLayout_8.addWidget(self.label_Multiplicity_2, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_charge_2 = QtWidgets.QLabel(self.create_vdata_groupbox_2)
        self.label_charge_2.setObjectName("label_charge_2")
        self.gridLayout_8.addWidget(self.label_charge_2, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_grid_spacing = QtWidgets.QLabel(self.create_vdata_groupbox_2)
        self.label_grid_spacing.setObjectName("label_grid_spacing")
        self.gridLayout_8.addWidget(self.label_grid_spacing, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_grid_spacing = QtWidgets.QLineEdit(self.create_vdata_groupbox_2)
        self.lineEdit_grid_spacing.setObjectName("lineEdit_grid_spacing")
        self.gridLayout_8.addWidget(self.lineEdit_grid_spacing, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.comboBox_basis_2 = QtWidgets.QComboBox(self.create_vdata_groupbox_2)
        self.comboBox_basis_2.setObjectName("comboBox_basis_2")
        self.comboBox_basis_2.addItem("")
        self.comboBox_basis_2.addItem("")
        self.comboBox_basis_2.addItem("")
        self.comboBox_basis_2.addItem("")
        self.comboBox_basis_2.addItem("")
        self.comboBox_basis_2.addItem("")
        self.comboBox_basis_2.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_basis_2, 1, 3, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_8)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushbutton_creat_psi4_dat = QtWidgets.QPushButton(self.create_vdata_groupbox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushbutton_creat_psi4_dat.sizePolicy().hasHeightForWidth())
        self.pushbutton_creat_psi4_dat.setSizePolicy(sizePolicy)
        self.pushbutton_creat_psi4_dat.setMinimumSize(QtCore.QSize(50, 65))
        self.pushbutton_creat_psi4_dat.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushbutton_creat_psi4_dat.setObjectName("pushbutton_creat_psi4_dat")
        self.verticalLayout_3.addWidget(self.pushbutton_creat_psi4_dat)
        self.pushbutton_compute = QtWidgets.QPushButton(self.create_vdata_groupbox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushbutton_compute.sizePolicy().hasHeightForWidth())
        self.pushbutton_compute.setSizePolicy(sizePolicy)
        self.pushbutton_compute.setMinimumSize(QtCore.QSize(20, 33))
        self.pushbutton_compute.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushbutton_compute.setObjectName("pushbutton_compute")
        self.verticalLayout_3.addWidget(self.pushbutton_compute)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addWidget(self.create_vdata_groupbox_2)
        self.target_setting_groupbox_2 = QtWidgets.QGroupBox(self.Dihedral)
        self.target_setting_groupbox_2.setObjectName("target_setting_groupbox_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.target_setting_groupbox_2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lineEdit_energy = QtWidgets.QLineEdit(self.target_setting_groupbox_2)
        self.lineEdit_energy.setObjectName("lineEdit_energy")
        self.gridLayout_9.addWidget(self.lineEdit_energy, 0, 3, 1, 1)
        self.lineEdit_weight_2 = QtWidgets.QLineEdit(self.target_setting_groupbox_2)
        self.lineEdit_weight_2.setObjectName("lineEdit_weight_2")
        self.gridLayout_9.addWidget(self.lineEdit_weight_2, 0, 1, 1, 1)
        self.label_energy = QtWidgets.QLabel(self.target_setting_groupbox_2)
        self.label_energy.setObjectName("label_energy")
        self.gridLayout_9.addWidget(self.label_energy, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_w_energy = QtWidgets.QLabel(self.target_setting_groupbox_2)
        self.label_w_energy.setObjectName("label_w_energy")
        self.gridLayout_9.addWidget(self.label_w_energy, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.weight_label_2 = QtWidgets.QLabel(self.target_setting_groupbox_2)
        self.weight_label_2.setObjectName("weight_label_2")
        self.gridLayout_9.addWidget(self.weight_label_2, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_w_energy = QtWidgets.QLineEdit(self.target_setting_groupbox_2)
        self.lineEdit_w_energy.setObjectName("lineEdit_w_energy")
        self.gridLayout_9.addWidget(self.lineEdit_w_energy, 1, 3, 1, 1)
        self.label_force = QtWidgets.QLabel(self.target_setting_groupbox_2)
        self.label_force.setObjectName("label_force")
        self.gridLayout_9.addWidget(self.label_force, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_w_force = QtWidgets.QLabel(self.target_setting_groupbox_2)
        self.label_w_force.setObjectName("label_w_force")
        self.gridLayout_9.addWidget(self.label_w_force, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_w_force = QtWidgets.QLineEdit(self.target_setting_groupbox_2)
        self.lineEdit_w_force.setObjectName("lineEdit_w_force")
        self.gridLayout_9.addWidget(self.lineEdit_w_force, 2, 1, 1, 1)
        self.lineEdit_force = QtWidgets.QLineEdit(self.target_setting_groupbox_2)
        self.lineEdit_force.setObjectName("lineEdit_force")
        self.gridLayout_9.addWidget(self.lineEdit_force, 1, 1, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_9)
        self.verticalLayout_4.addWidget(self.target_setting_groupbox_2)
        self.run_button_2 = QtWidgets.QPushButton(self.Dihedral)
        self.run_button_2.setObjectName("run_button_2")
        self.verticalLayout_4.addWidget(self.run_button_2)
        self.tabWidget.addTab(self.Dihedral, "")
        self.Lennard_Jones = QtWidgets.QWidget()
        self.Lennard_Jones.setObjectName("Lennard_Jones")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Lennard_Jones)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_project_3 = QtWidgets.QGroupBox(self.Lennard_Jones)
        self.groupBox_project_3.setObjectName("groupBox_project_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_project_3)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_project_name_3 = QtWidgets.QLabel(self.groupBox_project_3)
        self.label_project_name_3.setObjectName("label_project_name_3")
        self.gridLayout_10.addWidget(self.label_project_name_3, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_project_name_3 = QtWidgets.QLineEdit(self.groupBox_project_3)
        self.lineEdit_project_name_3.setObjectName("lineEdit_project_name_3")
        self.gridLayout_10.addWidget(self.lineEdit_project_name_3, 0, 1, 1, 1)
        self.pushButton_project_folder_3 = QtWidgets.QPushButton(self.groupBox_project_3)
        self.pushButton_project_folder_3.setObjectName("pushButton_project_folder_3")
        self.gridLayout_10.addWidget(self.pushButton_project_folder_3, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_project_folder_3 = QtWidgets.QLineEdit(self.groupBox_project_3)
        self.lineEdit_project_folder_3.setObjectName("lineEdit_project_folder_3")
        self.gridLayout_10.addWidget(self.lineEdit_project_folder_3, 1, 1, 1, 1)
        self.horizontalLayout_12.addLayout(self.gridLayout_10)
        self.pushButton_create_folder_3 = QtWidgets.QPushButton(self.groupBox_project_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_create_folder_3.sizePolicy().hasHeightForWidth())
        self.pushButton_create_folder_3.setSizePolicy(sizePolicy)
        self.pushButton_create_folder_3.setObjectName("pushButton_create_folder_3")
        self.horizontalLayout_12.addWidget(self.pushButton_create_folder_3)
        self.verticalLayout_6.addWidget(self.groupBox_project_3)
        self.groupBox_input_3 = QtWidgets.QGroupBox(self.Lennard_Jones)
        self.groupBox_input_3.setObjectName("groupBox_input_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_input_3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_topology_file_3 = QtWidgets.QLabel(self.groupBox_input_3)
        self.label_topology_file_3.setObjectName("label_topology_file_3")
        self.gridLayout_11.addWidget(self.label_topology_file_3, 0, 0, 1, 1)
        self.browse_coodrinate_3 = QtWidgets.QPushButton(self.groupBox_input_3)
        self.browse_coodrinate_3.setObjectName("browse_coodrinate_3")
        self.gridLayout_11.addWidget(self.browse_coodrinate_3, 1, 2, 1, 1)
        self.label_coordinate_file_3 = QtWidgets.QLabel(self.groupBox_input_3)
        self.label_coordinate_file_3.setObjectName("label_coordinate_file_3")
        self.gridLayout_11.addWidget(self.label_coordinate_file_3, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_topology_file_3 = QtWidgets.QLineEdit(self.groupBox_input_3)
        self.lineEdit_topology_file_3.setObjectName("lineEdit_topology_file_3")
        self.gridLayout_11.addWidget(self.lineEdit_topology_file_3, 0, 1, 1, 1)
        self.browse_topology_browse_3 = QtWidgets.QPushButton(self.groupBox_input_3)
        self.browse_topology_browse_3.setObjectName("browse_topology_browse_3")
        self.gridLayout_11.addWidget(self.browse_topology_browse_3, 0, 2, 1, 1)
        self.coordinate_file_Edit_3 = QtWidgets.QLineEdit(self.groupBox_input_3)
        self.coordinate_file_Edit_3.setObjectName("coordinate_file_Edit_3")
        self.gridLayout_11.addWidget(self.coordinate_file_Edit_3, 1, 1, 1, 1)
        self.horizontalLayout_13.addLayout(self.gridLayout_11)
        self.pushButton_process_input_3 = QtWidgets.QPushButton(self.groupBox_input_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_process_input_3.sizePolicy().hasHeightForWidth())
        self.pushButton_process_input_3.setSizePolicy(sizePolicy)
        self.pushButton_process_input_3.setObjectName("pushButton_process_input_3")
        self.horizontalLayout_13.addWidget(self.pushButton_process_input_3)
        self.verticalLayout_6.addWidget(self.groupBox_input_3)
        self.groupBox_select_atoms_3 = QtWidgets.QGroupBox(self.Lennard_Jones)
        self.groupBox_select_atoms_3.setObjectName("groupBox_select_atoms_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_select_atoms_3)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_sigma = QtWidgets.QLabel(self.groupBox_select_atoms_3)
        self.label_sigma.setObjectName("label_sigma")
        self.gridLayout_12.addWidget(self.label_sigma, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_sigma = QtWidgets.QLineEdit(self.groupBox_select_atoms_3)
        self.lineEdit_sigma.setObjectName("lineEdit_sigma")
        self.gridLayout_12.addWidget(self.lineEdit_sigma, 0, 1, 1, 1)
        self.label_epsilon = QtWidgets.QLabel(self.groupBox_select_atoms_3)
        self.label_epsilon.setObjectName("label_epsilon")
        self.gridLayout_12.addWidget(self.label_epsilon, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_epsilon = QtWidgets.QLineEdit(self.groupBox_select_atoms_3)
        self.lineEdit_epsilon.setObjectName("lineEdit_epsilon")
        self.gridLayout_12.addWidget(self.lineEdit_epsilon, 1, 1, 1, 1)
        self.horizontalLayout_15.addLayout(self.gridLayout_12)
        self.pushButton_process_itp = QtWidgets.QPushButton(self.groupBox_select_atoms_3)
        self.pushButton_process_itp.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_process_itp.sizePolicy().hasHeightForWidth())
        self.pushButton_process_itp.setSizePolicy(sizePolicy)
        self.pushButton_process_itp.setObjectName("pushButton_process_itp")
        self.horizontalLayout_15.addWidget(self.pushButton_process_itp)
        self.verticalLayout_6.addWidget(self.groupBox_select_atoms_3)
        self.groupBox_density_vap = QtWidgets.QGroupBox(self.Lennard_Jones)
        self.groupBox_density_vap.setObjectName("groupBox_density_vap")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_density_vap)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_density = QtWidgets.QLabel(self.groupBox_density_vap)
        self.label_density.setObjectName("label_density")
        self.gridLayout_13.addWidget(self.label_density, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_density = QtWidgets.QLineEdit(self.groupBox_density_vap)
        self.lineEdit_density.setObjectName("lineEdit_density")
        self.gridLayout_13.addWidget(self.lineEdit_density, 0, 1, 1, 1)
        self.label_enthalpy_of_vaporization = QtWidgets.QLabel(self.groupBox_density_vap)
        self.label_enthalpy_of_vaporization.setObjectName("label_enthalpy_of_vaporization")
        self.gridLayout_13.addWidget(self.label_enthalpy_of_vaporization, 1, 0, 1, 1)
        self.lineEdit_enthalpy_of_vaporization = QtWidgets.QLineEdit(self.groupBox_density_vap)
        self.lineEdit_enthalpy_of_vaporization.setObjectName("lineEdit_enthalpy_of_vaporization")
        self.gridLayout_13.addWidget(self.lineEdit_enthalpy_of_vaporization, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_13)
        self.pushButton_start_modeling = QtWidgets.QPushButton(self.groupBox_density_vap)
        self.pushButton_start_modeling.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start_modeling.sizePolicy().hasHeightForWidth())
        self.pushButton_start_modeling.setSizePolicy(sizePolicy)
        self.pushButton_start_modeling.setObjectName("pushButton_start_modeling")
        self.horizontalLayout_5.addWidget(self.pushButton_start_modeling)
        self.verticalLayout_6.addWidget(self.groupBox_density_vap)
        self.target_setting_groupbox_3 = QtWidgets.QGroupBox(self.Lennard_Jones)
        self.target_setting_groupbox_3.setObjectName("target_setting_groupbox_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.target_setting_groupbox_3)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_gas_md_steps = QtWidgets.QLabel(self.target_setting_groupbox_3)
        self.label_gas_md_steps.setObjectName("label_gas_md_steps")
        self.gridLayout_14.addWidget(self.label_gas_md_steps, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_gas_md_steps = QtWidgets.QLineEdit(self.target_setting_groupbox_3)
        self.lineEdit_gas_md_steps.setObjectName("lineEdit_gas_md_steps")
        self.gridLayout_14.addWidget(self.lineEdit_gas_md_steps, 1, 3, 1, 1)
        self.lineEdit_liquid_md_steps = QtWidgets.QLineEdit(self.target_setting_groupbox_3)
        self.lineEdit_liquid_md_steps.setObjectName("lineEdit_liquid_md_steps")
        self.gridLayout_14.addWidget(self.lineEdit_liquid_md_steps, 0, 5, 1, 1)
        self.label_liquid_timestep = QtWidgets.QLabel(self.target_setting_groupbox_3)
        self.label_liquid_timestep.setObjectName("label_liquid_timestep")
        self.gridLayout_14.addWidget(self.label_liquid_timestep, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_gas_timestep = QtWidgets.QLabel(self.target_setting_groupbox_3)
        self.label_gas_timestep.setObjectName("label_gas_timestep")
        self.gridLayout_14.addWidget(self.label_gas_timestep, 1, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_liquid_eq_steps = QtWidgets.QLabel(self.target_setting_groupbox_3)
        self.label_liquid_eq_steps.setObjectName("label_liquid_eq_steps")
        self.gridLayout_14.addWidget(self.label_liquid_eq_steps, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_gas_timestep = QtWidgets.QLineEdit(self.target_setting_groupbox_3)
        self.lineEdit_gas_timestep.setObjectName("lineEdit_gas_timestep")
        self.gridLayout_14.addWidget(self.lineEdit_gas_timestep, 1, 5, 1, 1)
        self.lineEdit_weight_3 = QtWidgets.QLineEdit(self.target_setting_groupbox_3)
        self.lineEdit_weight_3.setObjectName("lineEdit_weight_3")
        self.gridLayout_14.addWidget(self.lineEdit_weight_3, 0, 1, 1, 1)
        self.label_liquid_md_steps = QtWidgets.QLabel(self.target_setting_groupbox_3)
        self.label_liquid_md_steps.setObjectName("label_liquid_md_steps")
        self.gridLayout_14.addWidget(self.label_liquid_md_steps, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.weight_label_3 = QtWidgets.QLabel(self.target_setting_groupbox_3)
        self.weight_label_3.setObjectName("weight_label_3")
        self.gridLayout_14.addWidget(self.weight_label_3, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_liquid_timestep = QtWidgets.QLineEdit(self.target_setting_groupbox_3)
        self.lineEdit_liquid_timestep.setObjectName("lineEdit_liquid_timestep")
        self.gridLayout_14.addWidget(self.lineEdit_liquid_timestep, 1, 1, 1, 1)
        self.lineEdit_liquid_eq_steps = QtWidgets.QLineEdit(self.target_setting_groupbox_3)
        self.lineEdit_liquid_eq_steps.setObjectName("lineEdit_liquid_eq_steps")
        self.gridLayout_14.addWidget(self.lineEdit_liquid_eq_steps, 0, 3, 1, 1)
        self.label_w_rho = QtWidgets.QLabel(self.target_setting_groupbox_3)
        self.label_w_rho.setObjectName("label_w_rho")
        self.gridLayout_14.addWidget(self.label_w_rho, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_w_rho = QtWidgets.QLineEdit(self.target_setting_groupbox_3)
        self.lineEdit_w_rho.setObjectName("lineEdit_w_rho")
        self.gridLayout_14.addWidget(self.lineEdit_w_rho, 2, 1, 1, 1)
        self.label_w_hvap = QtWidgets.QLabel(self.target_setting_groupbox_3)
        self.label_w_hvap.setObjectName("label_w_hvap")
        self.gridLayout_14.addWidget(self.label_w_hvap, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_w_hvap = QtWidgets.QLineEdit(self.target_setting_groupbox_3)
        self.lineEdit_w_hvap.setObjectName("lineEdit_w_hvap")
        self.gridLayout_14.addWidget(self.lineEdit_w_hvap, 2, 3, 1, 1)
        self.label_md_threads = QtWidgets.QLabel(self.target_setting_groupbox_3)
        self.label_md_threads.setObjectName("label_md_threads")
        self.gridLayout_14.addWidget(self.label_md_threads, 2, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_md_threads = QtWidgets.QLineEdit(self.target_setting_groupbox_3)
        self.lineEdit_md_threads.setObjectName("lineEdit_md_threads")
        self.gridLayout_14.addWidget(self.lineEdit_md_threads, 2, 5, 1, 1)
        self.horizontalLayout_16.addLayout(self.gridLayout_14)
        self.verticalLayout_6.addWidget(self.target_setting_groupbox_3)
        self.run_button_3 = QtWidgets.QPushButton(self.Lennard_Jones)
        self.run_button_3.setObjectName("run_button_3")
        self.verticalLayout_6.addWidget(self.run_button_3)
        self.tabWidget.addTab(self.Lennard_Jones, "")
        self.Analyze = QtWidgets.QWidget()
        self.Analyze.setObjectName("Analyze")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Analyze)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setHorizontalSpacing(10)
        self.gridLayout_15.setVerticalSpacing(20)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_Score = QtWidgets.QLabel(self.Analyze)
        self.label_Score.setObjectName("label_Score")
        self.gridLayout_15.addWidget(self.label_Score, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_energy_difference = QtWidgets.QLineEdit(self.Analyze)
        self.lineEdit_energy_difference.setObjectName("lineEdit_energy_difference")
        self.gridLayout_15.addWidget(self.lineEdit_energy_difference, 4, 1, 1, 1)
        self.label_rmsd = QtWidgets.QLabel(self.Analyze)
        self.label_rmsd.setObjectName("label_rmsd")
        self.gridLayout_15.addWidget(self.label_rmsd, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_energy_difference = QtWidgets.QLabel(self.Analyze)
        self.label_energy_difference.setObjectName("label_energy_difference")
        self.gridLayout_15.addWidget(self.label_energy_difference, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_rmsd = QtWidgets.QLineEdit(self.Analyze)
        self.lineEdit_rmsd.setObjectName("lineEdit_rmsd")
        self.gridLayout_15.addWidget(self.lineEdit_rmsd, 2, 1, 1, 1)
        self.pushButton_browse_Score = QtWidgets.QPushButton(self.Analyze)
        self.pushButton_browse_Score.setObjectName("pushButton_browse_Score")
        self.gridLayout_15.addWidget(self.pushButton_browse_Score, 0, 2, 1, 1)
        self.pushButton_browse_rmsd = QtWidgets.QPushButton(self.Analyze)
        self.pushButton_browse_rmsd.setObjectName("pushButton_browse_rmsd")
        self.gridLayout_15.addWidget(self.pushButton_browse_rmsd, 2, 2, 1, 1)
        self.lineEdit_Score = QtWidgets.QLineEdit(self.Analyze)
        self.lineEdit_Score.setObjectName("lineEdit_Score")
        self.gridLayout_15.addWidget(self.lineEdit_Score, 0, 1, 1, 1)
        self.pushButton_browse_vibration_mode = QtWidgets.QPushButton(self.Analyze)
        self.pushButton_browse_vibration_mode.setObjectName("pushButton_browse_vibration_mode")
        self.gridLayout_15.addWidget(self.pushButton_browse_vibration_mode, 3, 2, 1, 1)
        self.label_Grad = QtWidgets.QLabel(self.Analyze)
        self.label_Grad.setObjectName("label_Grad")
        self.gridLayout_15.addWidget(self.label_Grad, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_browse_density_hvap = QtWidgets.QPushButton(self.Analyze)
        self.pushButton_browse_density_hvap.setObjectName("pushButton_browse_density_hvap")
        self.gridLayout_15.addWidget(self.pushButton_browse_density_hvap, 5, 2, 1, 1)
        self.label_vibration_mode = QtWidgets.QLabel(self.Analyze)
        self.label_vibration_mode.setObjectName("label_vibration_mode")
        self.gridLayout_15.addWidget(self.label_vibration_mode, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_browse_energy_difference = QtWidgets.QPushButton(self.Analyze)
        self.pushButton_browse_energy_difference.setObjectName("pushButton_browse_energy_difference")
        self.gridLayout_15.addWidget(self.pushButton_browse_energy_difference, 4, 2, 1, 1)
        self.lineEdit_Grad = QtWidgets.QLineEdit(self.Analyze)
        self.lineEdit_Grad.setObjectName("lineEdit_Grad")
        self.gridLayout_15.addWidget(self.lineEdit_Grad, 1, 1, 1, 1)
        self.lineEdit_vibration_mode = QtWidgets.QLineEdit(self.Analyze)
        self.lineEdit_vibration_mode.setObjectName("lineEdit_vibration_mode")
        self.gridLayout_15.addWidget(self.lineEdit_vibration_mode, 3, 1, 1, 1)
        self.lineEdit_density_hvap = QtWidgets.QLineEdit(self.Analyze)
        self.lineEdit_density_hvap.setObjectName("lineEdit_density_hvap")
        self.gridLayout_15.addWidget(self.lineEdit_density_hvap, 5, 1, 1, 1)
        self.label_density_hvap = QtWidgets.QLabel(self.Analyze)
        self.label_density_hvap.setObjectName("label_density_hvap")
        self.gridLayout_15.addWidget(self.label_density_hvap, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_browse_Grad = QtWidgets.QPushButton(self.Analyze)
        self.pushButton_browse_Grad.setObjectName("pushButton_browse_Grad")
        self.gridLayout_15.addWidget(self.pushButton_browse_Grad, 1, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_15)
        spacerItem = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.pushButton_view_plot = QtWidgets.QPushButton(self.Analyze)
        self.pushButton_view_plot.setObjectName("pushButton_view_plot")
        self.verticalLayout_5.addWidget(self.pushButton_view_plot)
        self.tabWidget.addTab(self.Analyze, "")
        self.verticalLayout_7.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 543, 23))
        self.menubar.setObjectName("menubar")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Psi4_global_Setting = QtWidgets.QAction(MainWindow)
        self.action_Psi4_global_Setting.setObjectName("action_Psi4_global_Setting")
        self.action_Forcebalance_global_Setting = QtWidgets.QAction(MainWindow)
        self.action_Forcebalance_global_Setting.setObjectName("action_Forcebalance_global_Setting")
        self.actionDenom_Setting = QtWidgets.QAction(MainWindow)
        self.actionDenom_Setting.setObjectName("actionDenom_Setting")
        self.menuSetting.addAction(self.action_Psi4_global_Setting)
        self.menuSetting.addAction(self.action_Forcebalance_global_Setting)
        self.menuSetting.addAction(self.actionDenom_Setting)
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_method.setCurrentIndex(0)
        self.comboBox_method_2.setCurrentIndex(0)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ParaRefine-GUI v0.0.1"))
        self.groupBox_project.setTitle(_translate("MainWindow", "Project"))
        self.label_project_name.setText(_translate("MainWindow", "Project Name"))
        self.pushButton_project_folder.setText(_translate("MainWindow", "Project Folder"))
        self.pushButton_create_folder.setText(_translate("MainWindow", "Create Folder"))
        self.groupBox_input.setTitle(_translate("MainWindow", "Input"))
        self.label_topology_file.setText(_translate("MainWindow", "Topology File"))
        self.browse_coodrinate.setText(_translate("MainWindow", "Browse"))
        self.label_coordinate_file.setText(_translate("MainWindow", "Coordinate File"))
        self.browse_topology_browse.setText(_translate("MainWindow", "Browse"))
        self.pushButton_process_input.setText(_translate("MainWindow", "Process Input"))
        self.create_vdata_groupbox.setTitle(_translate("MainWindow", "Creat Vdata"))
        self.label_Multiplicity.setText(_translate("MainWindow", "Multiplicity"))
        self.label_charge.setText(_translate("MainWindow", "Charge"))
        self.lineEdit_Multiplicity.setText(_translate("MainWindow", "1"))
        self.lineEdit_charge.setText(_translate("MainWindow", "0"))
        self.method_label.setText(_translate("MainWindow", "Method"))
        self.comboBox_method.setCurrentText(_translate("MainWindow", "hf"))
        self.comboBox_method.setItemText(0, _translate("MainWindow", "hf"))
        self.comboBox_method.setItemText(1, _translate("MainWindow", "b3lyp"))
        self.comboBox_method.setItemText(2, _translate("MainWindow", "b3lyp-d3bj"))
        self.comboBox_method.setItemText(3, _translate("MainWindow", "m06-2x"))
        self.comboBox_method.setItemText(4, _translate("MainWindow", "wb97x-d"))
        self.comboBox_method.setItemText(5, _translate("MainWindow", "mp2"))
        self.comboBox_method.setItemText(6, _translate("MainWindow", "ccsd(t)"))
        self.basis_label.setText(_translate("MainWindow", "Basis"))
        self.comboBox_basis.setItemText(0, _translate("MainWindow", "6-31g(d)"))
        self.comboBox_basis.setItemText(1, _translate("MainWindow", "6-311+g(d,p)"))
        self.comboBox_basis.setItemText(2, _translate("MainWindow", "cc-pvdz"))
        self.comboBox_basis.setItemText(3, _translate("MainWindow", "cc-pvtz"))
        self.comboBox_basis.setItemText(4, _translate("MainWindow", "aug-cc-pvtz"))
        self.comboBox_basis.setItemText(5, _translate("MainWindow", "def2-svp"))
        self.comboBox_basis.setItemText(6, _translate("MainWindow", "def2-tzvp"))
        self.compute_button.setText(_translate("MainWindow", "Compute"))
        self.groupBox_select_atoms.setTitle(_translate("MainWindow", "Select Atoms"))
        self.label_angles.setText(_translate("MainWindow", "Angles"))
        self.label_bonds.setText(_translate("MainWindow", "Bonds"))
        self.label_removed_frequency.setText(_translate("MainWindow", "Removed Frequency"))
        self.checkBox_select_all.setText(_translate("MainWindow", "Select All"))
        self.pushButton_view_vibration.setText(_translate("MainWindow", "View vibration"))
        self.target_setting_groupbox.setTitle(_translate("MainWindow", "Target Setting"))
        self.wavenumber_tol_label.setText(_translate("MainWindow", "Wavenumber_tol"))
        self.lineEdit_weight.setText(_translate("MainWindow", "1"))
        self.cm1_label.setText(_translate("MainWindow", "cm<sup>-1<sup>"))
        self.browse_user_vdata.setText(_translate("MainWindow", "Browse"))
        self.lineEdit_wavenumber.setText(_translate("MainWindow", "200"))
        self.user_vdata_label.setText(_translate("MainWindow", "user vdata(optional)"))
        self.weight_label.setText(_translate("MainWindow", "Weight"))
        self.comboBox_reassign_modes.setItemText(0, _translate("MainWindow", "permute"))
        self.comboBox_reassign_modes.setItemText(1, _translate("MainWindow", "overlap"))
        self.label_reassigan_mode.setText(_translate("MainWindow", "reassign_modes"))
        self.run_button.setText(_translate("MainWindow", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Bonds_Angles), _translate("MainWindow", "Bonds && Angles"))
        self.groupBox_project_2.setTitle(_translate("MainWindow", "Project"))
        self.label_project_name_2.setText(_translate("MainWindow", "Project Name"))
        self.pushButton_project_folder_2.setText(_translate("MainWindow", "Project Folder"))
        self.pushButton_create_folder_2.setText(_translate("MainWindow", "Create Folder"))
        self.groupBox_input_2.setTitle(_translate("MainWindow", "Input"))
        self.label_topology_file_2.setText(_translate("MainWindow", "Topology File"))
        self.browse_coodrinate_2.setText(_translate("MainWindow", "Browse"))
        self.label_coordinate_file_2.setText(_translate("MainWindow", "Coordinate File"))
        self.browse_topology_browse_2.setText(_translate("MainWindow", "Browse"))
        self.pushButton_process_input_2.setText(_translate("MainWindow", "Process Input"))
        self.groupBox_select_atoms_2.setTitle(_translate("MainWindow", "Select Atoms"))
        self.label_dihedral_angle.setText(_translate("MainWindow", "Dihedral Angle"))
        self.pushButton_view_dihedral.setText(_translate("MainWindow", "view"))
        self.create_vdata_groupbox_2.setTitle(_translate("MainWindow", "Creat Qdata"))
        self.lineEdit_charge_2.setText(_translate("MainWindow", "0"))
        self.lineEdit_Multiplicity_2.setText(_translate("MainWindow", "1"))
        self.comboBox_method_2.setCurrentText(_translate("MainWindow", "hf"))
        self.comboBox_method_2.setItemText(0, _translate("MainWindow", "hf"))
        self.comboBox_method_2.setItemText(1, _translate("MainWindow", "b3lyp"))
        self.comboBox_method_2.setItemText(2, _translate("MainWindow", "b3lyp-d3bj"))
        self.comboBox_method_2.setItemText(3, _translate("MainWindow", "m06-2x"))
        self.comboBox_method_2.setItemText(4, _translate("MainWindow", "wb97x-d"))
        self.comboBox_method_2.setItemText(5, _translate("MainWindow", "mp2"))
        self.comboBox_method_2.setItemText(6, _translate("MainWindow", "ccsd(t)"))
        self.basis_label_2.setText(_translate("MainWindow", "Basis"))
        self.method_label_2.setText(_translate("MainWindow", "Method"))
        self.label_Multiplicity_2.setText(_translate("MainWindow", "Multiplicity"))
        self.label_charge_2.setText(_translate("MainWindow", "Charge"))
        self.label_grid_spacing.setText(_translate("MainWindow", "Grid Spacing"))
        self.lineEdit_grid_spacing.setText(_translate("MainWindow", "15"))
        self.comboBox_basis_2.setItemText(0, _translate("MainWindow", "6-31g(d)"))
        self.comboBox_basis_2.setItemText(1, _translate("MainWindow", "6-311+g(d,p)"))
        self.comboBox_basis_2.setItemText(2, _translate("MainWindow", "cc-pvdz"))
        self.comboBox_basis_2.setItemText(3, _translate("MainWindow", "cc-pvtz"))
        self.comboBox_basis_2.setItemText(4, _translate("MainWindow", "aug-cc-pvtz"))
        self.comboBox_basis_2.setItemText(5, _translate("MainWindow", "def2-svp"))
        self.comboBox_basis_2.setItemText(6, _translate("MainWindow", "def2-tzvp"))
        self.pushbutton_creat_psi4_dat.setText(_translate("MainWindow", "creat psi4 dat"))
        self.pushbutton_compute.setText(_translate("MainWindow", "compute"))
        self.target_setting_groupbox_2.setTitle(_translate("MainWindow", "Target Setting"))
        self.lineEdit_energy.setText(_translate("MainWindow", "1"))
        self.lineEdit_weight_2.setText(_translate("MainWindow", "1"))
        self.label_energy.setText(_translate("MainWindow", "energy"))
        self.label_w_energy.setText(_translate("MainWindow", "w_energy"))
        self.weight_label_2.setText(_translate("MainWindow", "weight"))
        self.lineEdit_w_energy.setText(_translate("MainWindow", "1"))
        self.label_force.setText(_translate("MainWindow", "force"))
        self.label_w_force.setText(_translate("MainWindow", "w_force"))
        self.lineEdit_w_force.setText(_translate("MainWindow", "1"))
        self.lineEdit_force.setText(_translate("MainWindow", "0"))
        self.run_button_2.setText(_translate("MainWindow", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Dihedral), _translate("MainWindow", "Dihedral"))
        self.groupBox_project_3.setTitle(_translate("MainWindow", "Project"))
        self.label_project_name_3.setText(_translate("MainWindow", "Project Name"))
        self.pushButton_project_folder_3.setText(_translate("MainWindow", "Project Folder"))
        self.pushButton_create_folder_3.setText(_translate("MainWindow", "Create Folder"))
        self.groupBox_input_3.setTitle(_translate("MainWindow", "Input"))
        self.label_topology_file_3.setText(_translate("MainWindow", "Topology File"))
        self.browse_coodrinate_3.setText(_translate("MainWindow", "Browse"))
        self.label_coordinate_file_3.setText(_translate("MainWindow", "Coordinate File"))
        self.browse_topology_browse_3.setText(_translate("MainWindow", "Browse"))
        self.pushButton_process_input_3.setText(_translate("MainWindow", "Process Input"))
        self.groupBox_select_atoms_3.setTitle(_translate("MainWindow", "Select Atoms"))
        self.label_sigma.setText(_translate("MainWindow", "sigma"))
        self.label_epsilon.setText(_translate("MainWindow", "epsilon"))
        self.pushButton_process_itp.setText(_translate("MainWindow", "process itp"))
        self.groupBox_density_vap.setTitle(_translate("MainWindow", "Density && Vaporization"))
        self.label_density.setText(_translate("MainWindow", "Density"))
        self.label_enthalpy_of_vaporization.setText(_translate("MainWindow", "Enthalpy of Vaporization"))
        self.pushButton_start_modeling.setText(_translate("MainWindow", "Start Modeling"))
        self.target_setting_groupbox_3.setTitle(_translate("MainWindow", "Target Setting"))
        self.label_gas_md_steps.setText(_translate("MainWindow", "gas_md_steps"))
        self.lineEdit_gas_md_steps.setText(_translate("MainWindow", "200000"))
        self.lineEdit_liquid_md_steps.setText(_translate("MainWindow", "50000"))
        self.label_liquid_timestep.setText(_translate("MainWindow", "liquid_timestep"))
        self.label_gas_timestep.setText(_translate("MainWindow", "gas_timestep"))
        self.label_liquid_eq_steps.setText(_translate("MainWindow", "liquid_eq_steps"))
        self.lineEdit_gas_timestep.setText(_translate("MainWindow", "0.5"))
        self.lineEdit_weight_3.setText(_translate("MainWindow", "1"))
        self.label_liquid_md_steps.setText(_translate("MainWindow", "liquid_md_steps"))
        self.weight_label_3.setText(_translate("MainWindow", "weight"))
        self.lineEdit_liquid_timestep.setText(_translate("MainWindow", "1"))
        self.lineEdit_liquid_eq_steps.setText(_translate("MainWindow", "1000000"))
        self.label_w_rho.setText(_translate("MainWindow", "w_rho"))
        self.lineEdit_w_rho.setText(_translate("MainWindow", "1"))
        self.label_w_hvap.setText(_translate("MainWindow", "w_hvap"))
        self.lineEdit_w_hvap.setText(_translate("MainWindow", "1"))
        self.label_md_threads.setText(_translate("MainWindow", "md_threads"))
        self.lineEdit_md_threads.setText(_translate("MainWindow", "1"))
        self.run_button_3.setText(_translate("MainWindow", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Lennard_Jones), _translate("MainWindow", "Lennard-Jones"))
        self.label_Score.setText(_translate("MainWindow", "Score"))
        self.label_rmsd.setText(_translate("MainWindow", "RMSD"))
        self.label_energy_difference.setText(_translate("MainWindow", "Energy difference"))
        self.pushButton_browse_Score.setText(_translate("MainWindow", "Browse"))
        self.pushButton_browse_rmsd.setText(_translate("MainWindow", "Browse"))
        self.pushButton_browse_vibration_mode.setText(_translate("MainWindow", "Browse"))
        self.label_Grad.setText(_translate("MainWindow", "Grad"))
        self.pushButton_browse_density_hvap.setText(_translate("MainWindow", "Browse"))
        self.label_vibration_mode.setText(_translate("MainWindow", "Vibration  mode"))
        self.pushButton_browse_energy_difference.setText(_translate("MainWindow", "Browse"))
        self.label_density_hvap.setText(_translate("MainWindow", "Density & Hvap"))
        self.pushButton_browse_Grad.setText(_translate("MainWindow", "Browse"))
        self.pushButton_view_plot.setText(_translate("MainWindow", "view"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Analyze), _translate("MainWindow", "Analyze"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.action_Psi4_global_Setting.setText(_translate("MainWindow", "Psi4 Global Setting"))
        self.action_Forcebalance_global_Setting.setText(_translate("MainWindow", "Forcebalance Global Setting"))
        self.actionDenom_Setting.setText(_translate("MainWindow", "Denom Setting"))
class Ui_Dialog_psi4_global_setting(object):
    def setupUi(self, Dialog_psi4_global_setting):
        Dialog_psi4_global_setting.setObjectName("Dialog_psi4_global_setting")
        Dialog_psi4_global_setting.resize(272, 137)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog_psi4_global_setting)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog_psi4_global_setting)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_memory = QtWidgets.QLineEdit(Dialog_psi4_global_setting)
        self.lineEdit_memory.setObjectName("lineEdit_memory")
        self.gridLayout.addWidget(self.lineEdit_memory, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog_psi4_global_setting)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_cpu_number = QtWidgets.QLineEdit(Dialog_psi4_global_setting)
        self.lineEdit_cpu_number.setObjectName("lineEdit_cpu_number")
        self.gridLayout.addWidget(self.lineEdit_cpu_number, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.retranslateUi(Dialog_psi4_global_setting)
    def retranslateUi(self, Dialog_psi4_global_setting):
        _translate = QtCore.QCoreApplication.translate
        Dialog_psi4_global_setting.setWindowTitle(_translate("Dialog_psi4_global_setting", "Dialog"))
        self.label.setText(_translate("Dialog_psi4_global_setting", "Memory"))
        self.lineEdit_memory.setText(_translate("Dialog_psi4_global_setting", "4"))
        self.lineEdit_memory.setPlaceholderText(_translate("Dialog_psi4_global_setting", "unit: GB"))
        self.label_2.setText(_translate("Dialog_psi4_global_setting", "CPU Number"))
        self.lineEdit_cpu_number.setText(_translate("Dialog_psi4_global_setting", "4"))
class Ui_Dialog_fb_global(object):
    def setupUi(self, Dialog_fb_global):
        Dialog_fb_global.setObjectName("Dialog_fb_global")
        Dialog_fb_global.resize(437, 661)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog_fb_global)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_opt_con = QtWidgets.QGroupBox(Dialog_fb_global)
        self.groupBox_opt_con.setObjectName("groupBox_opt_con")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_opt_con)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_convergence_step = QtWidgets.QLabel(self.groupBox_opt_con)
        self.label_convergence_step.setObjectName("label_convergence_step")
        self.gridLayout.addWidget(self.label_convergence_step, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_criteria = QtWidgets.QLineEdit(self.groupBox_opt_con)
        self.lineEdit_criteria.setObjectName("lineEdit_criteria")
        self.gridLayout.addWidget(self.lineEdit_criteria, 0, 1, 1, 1)
        self.lineEdit_convergence_gradient = QtWidgets.QLineEdit(self.groupBox_opt_con)
        self.lineEdit_convergence_gradient.setObjectName("lineEdit_convergence_gradient")
        self.gridLayout.addWidget(self.lineEdit_convergence_gradient, 1, 1, 1, 1)
        self.lineEdit_convergence_step = QtWidgets.QLineEdit(self.groupBox_opt_con)
        self.lineEdit_convergence_step.setObjectName("lineEdit_convergence_step")
        self.gridLayout.addWidget(self.lineEdit_convergence_step, 2, 1, 1, 1)
        self.label_convergence_gradient = QtWidgets.QLabel(self.groupBox_opt_con)
        self.label_convergence_gradient.setObjectName("label_convergence_gradient")
        self.gridLayout.addWidget(self.label_convergence_gradient, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_criteria = QtWidgets.QLabel(self.groupBox_opt_con)
        self.label_criteria.setObjectName("label_criteria")
        self.gridLayout.addWidget(self.label_criteria, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_maxstep = QtWidgets.QLineEdit(self.groupBox_opt_con)
        self.lineEdit_maxstep.setObjectName("lineEdit_maxstep")
        self.gridLayout.addWidget(self.lineEdit_maxstep, 0, 3, 1, 1)
        self.label_convergence_objective = QtWidgets.QLabel(self.groupBox_opt_con)
        self.label_convergence_objective.setObjectName("label_convergence_objective")
        self.gridLayout.addWidget(self.label_convergence_objective, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_convergence_objective = QtWidgets.QLineEdit(self.groupBox_opt_con)
        self.lineEdit_convergence_objective.setObjectName("lineEdit_convergence_objective")
        self.gridLayout.addWidget(self.lineEdit_convergence_objective, 1, 3, 1, 1)
        self.label_maxstep = QtWidgets.QLabel(self.groupBox_opt_con)
        self.label_maxstep.setObjectName("label_maxstep")
        self.gridLayout.addWidget(self.label_maxstep, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox_opt_con)
        self.groupBox_opt_alg = QtWidgets.QGroupBox(Dialog_fb_global)
        self.groupBox_opt_alg.setObjectName("groupBox_opt_alg")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_opt_alg)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_adaptive_damping = QtWidgets.QLabel(self.groupBox_opt_alg)
        self.label_adaptive_damping.setObjectName("label_adaptive_damping")
        self.gridLayout_2.addWidget(self.label_adaptive_damping, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_trust0 = QtWidgets.QLineEdit(self.groupBox_opt_alg)
        self.lineEdit_trust0.setObjectName("lineEdit_trust0")
        self.gridLayout_2.addWidget(self.lineEdit_trust0, 0, 1, 1, 1)
        self.lineEdit_adaptive_damping = QtWidgets.QLineEdit(self.groupBox_opt_alg)
        self.lineEdit_adaptive_damping.setObjectName("lineEdit_adaptive_damping")
        self.gridLayout_2.addWidget(self.lineEdit_adaptive_damping, 1, 1, 1, 1)
        self.label_adaptive_factor = QtWidgets.QLabel(self.groupBox_opt_alg)
        self.label_adaptive_factor.setObjectName("label_adaptive_factor")
        self.gridLayout_2.addWidget(self.label_adaptive_factor, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_trust0 = QtWidgets.QLabel(self.groupBox_opt_alg)
        self.label_trust0.setObjectName("label_trust0")
        self.gridLayout_2.addWidget(self.label_trust0, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_mintrust = QtWidgets.QLabel(self.groupBox_opt_alg)
        self.label_mintrust.setObjectName("label_mintrust")
        self.gridLayout_2.addWidget(self.label_mintrust, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_adaptive_factor = QtWidgets.QLineEdit(self.groupBox_opt_alg)
        self.lineEdit_adaptive_factor.setObjectName("lineEdit_adaptive_factor")
        self.gridLayout_2.addWidget(self.lineEdit_adaptive_factor, 1, 3, 1, 1)
        self.lineEdit_mintrust = QtWidgets.QLineEdit(self.groupBox_opt_alg)
        self.lineEdit_mintrust.setObjectName("lineEdit_mintrust")
        self.gridLayout_2.addWidget(self.lineEdit_mintrust, 0, 3, 1, 1)
        self.label_eig_lowerbound = QtWidgets.QLabel(self.groupBox_opt_alg)
        self.label_eig_lowerbound.setObjectName("label_eig_lowerbound")
        self.gridLayout_2.addWidget(self.label_eig_lowerbound, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_eig_lowerbound = QtWidgets.QLineEdit(self.groupBox_opt_alg)
        self.lineEdit_eig_lowerbound.setObjectName("lineEdit_eig_lowerbound")
        self.gridLayout_2.addWidget(self.lineEdit_eig_lowerbound, 2, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox_opt_alg)
        self.groupBox = QtWidgets.QGroupBox(Dialog_fb_global)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_priors = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_priors.setObjectName("groupBox_priors")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_priors)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_BONDSB = QtWidgets.QLabel(self.groupBox_priors)
        self.label_BONDSB.setObjectName("label_BONDSB")
        self.gridLayout_4.addWidget(self.label_BONDSB, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_BONDSB = QtWidgets.QLineEdit(self.groupBox_priors)
        self.lineEdit_BONDSB.setObjectName("lineEdit_BONDSB")
        self.gridLayout_4.addWidget(self.lineEdit_BONDSB, 0, 1, 1, 1)
        self.label_BONDSK = QtWidgets.QLabel(self.groupBox_priors)
        self.label_BONDSK.setObjectName("label_BONDSK")
        self.gridLayout_4.addWidget(self.label_BONDSK, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_BONDSK = QtWidgets.QLineEdit(self.groupBox_priors)
        self.lineEdit_BONDSK.setObjectName("lineEdit_BONDSK")
        self.gridLayout_4.addWidget(self.lineEdit_BONDSK, 0, 3, 1, 1)
        self.label_ANGLESB = QtWidgets.QLabel(self.groupBox_priors)
        self.label_ANGLESB.setObjectName("label_ANGLESB")
        self.gridLayout_4.addWidget(self.label_ANGLESB, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_ANGLESB = QtWidgets.QLineEdit(self.groupBox_priors)
        self.lineEdit_ANGLESB.setObjectName("lineEdit_ANGLESB")
        self.gridLayout_4.addWidget(self.lineEdit_ANGLESB, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_priors)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_ANGLESK = QtWidgets.QLineEdit(self.groupBox_priors)
        self.lineEdit_ANGLESK.setObjectName("lineEdit_ANGLESK")
        self.gridLayout_4.addWidget(self.lineEdit_ANGLESK, 1, 3, 1, 1)
        self.label_PDIHS3B = QtWidgets.QLabel(self.groupBox_priors)
        self.label_PDIHS3B.setObjectName("label_PDIHS3B")
        self.gridLayout_4.addWidget(self.label_PDIHS3B, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_PDIHS3B = QtWidgets.QLineEdit(self.groupBox_priors)
        self.lineEdit_PDIHS3B.setObjectName("lineEdit_PDIHS3B")
        self.gridLayout_4.addWidget(self.lineEdit_PDIHS3B, 2, 1, 1, 1)
        self.label_PDIHS3K = QtWidgets.QLabel(self.groupBox_priors)
        self.label_PDIHS3K.setObjectName("label_PDIHS3K")
        self.gridLayout_4.addWidget(self.label_PDIHS3K, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_PDIHS3K = QtWidgets.QLineEdit(self.groupBox_priors)
        self.lineEdit_PDIHS3K.setObjectName("lineEdit_PDIHS3K")
        self.gridLayout_4.addWidget(self.lineEdit_PDIHS3K, 2, 3, 1, 1)
        self.label_VDWS = QtWidgets.QLabel(self.groupBox_priors)
        self.label_VDWS.setObjectName("label_VDWS")
        self.gridLayout_4.addWidget(self.label_VDWS, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_VDWS = QtWidgets.QLineEdit(self.groupBox_priors)
        self.lineEdit_VDWS.setObjectName("lineEdit_VDWS")
        self.gridLayout_4.addWidget(self.lineEdit_VDWS, 3, 1, 1, 1)
        self.label_VDWT = QtWidgets.QLabel(self.groupBox_priors)
        self.label_VDWT.setObjectName("label_VDWT")
        self.gridLayout_4.addWidget(self.label_VDWT, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_VDWT = QtWidgets.QLineEdit(self.groupBox_priors)
        self.lineEdit_VDWT.setObjectName("lineEdit_VDWT")
        self.gridLayout_4.addWidget(self.lineEdit_VDWT, 3, 3, 1, 1)
        self.label_COUL = QtWidgets.QLabel(self.groupBox_priors)
        self.label_COUL.setObjectName("label_COUL")
        self.gridLayout_4.addWidget(self.label_COUL, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_COUL = QtWidgets.QLineEdit(self.groupBox_priors)
        self.lineEdit_COUL.setObjectName("lineEdit_COUL")
        self.gridLayout_4.addWidget(self.lineEdit_COUL, 4, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.groupBox_priors)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_penalty_additive = QtWidgets.QLabel(self.groupBox_2)
        self.label_penalty_additive.setObjectName("label_penalty_additive")
        self.gridLayout_3.addWidget(self.label_penalty_additive, 0, 2, 1, 1)
        self.label_normalize_weights = QtWidgets.QLabel(self.groupBox_2)
        self.label_normalize_weights.setObjectName("label_normalize_weights")
        self.gridLayout_3.addWidget(self.label_normalize_weights, 1, 0, 1, 1)
        self.label_penalty_type = QtWidgets.QLabel(self.groupBox_2)
        self.label_penalty_type.setObjectName("label_penalty_type")
        self.gridLayout_3.addWidget(self.label_penalty_type, 0, 0, 1, 1)
        self.comboBox_penalty_type = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_penalty_type.setObjectName("comboBox_penalty_type")
        self.comboBox_penalty_type.addItem("")
        self.comboBox_penalty_type.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_penalty_type, 0, 1, 1, 1)
        self.lineEdit_penalty_additive = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_penalty_additive.setObjectName("lineEdit_penalty_additive")
        self.gridLayout_3.addWidget(self.lineEdit_penalty_additive, 0, 3, 1, 1)
        self.lineEdit_normalize_weights = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_normalize_weights.setObjectName("lineEdit_normalize_weights")
        self.gridLayout_3.addWidget(self.lineEdit_normalize_weights, 1, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.retranslateUi(Dialog_fb_global)
    def retranslateUi(self, Dialog_fb_global):
        _translate = QtCore.QCoreApplication.translate
        Dialog_fb_global.setWindowTitle(_translate("Dialog_fb_global", "Dialog"))
        self.groupBox_opt_con.setTitle(_translate("Dialog_fb_global", "Optimizer Convergence"))
        self.label_convergence_step.setText(_translate("Dialog_fb_global", "convergence_step"))
        self.lineEdit_criteria.setText(_translate("Dialog_fb_global", "1"))
        self.lineEdit_convergence_gradient.setText(_translate("Dialog_fb_global", "0.01"))
        self.lineEdit_convergence_step.setText(_translate("Dialog_fb_global", "0.01"))
        self.label_convergence_gradient.setText(_translate("Dialog_fb_global", "convergence_gradient"))
        self.label_criteria.setText(_translate("Dialog_fb_global", "criteria"))
        self.lineEdit_maxstep.setText(_translate("Dialog_fb_global", "100"))
        self.label_convergence_objective.setText(_translate("Dialog_fb_global", "convergence_objective"))
        self.lineEdit_convergence_objective.setText(_translate("Dialog_fb_global", "0.01"))
        self.label_maxstep.setText(_translate("Dialog_fb_global", "maxstep"))
        self.groupBox_opt_alg.setTitle(_translate("Dialog_fb_global", "Optimizer Algorithm"))
        self.label_adaptive_damping.setText(_translate("Dialog_fb_global", "adaptive_damping"))
        self.lineEdit_trust0.setText(_translate("Dialog_fb_global", "0.1"))
        self.lineEdit_adaptive_damping.setText(_translate("Dialog_fb_global", "1.0"))
        self.label_adaptive_factor.setText(_translate("Dialog_fb_global", "adaptive_factor"))
        self.label_trust0.setText(_translate("Dialog_fb_global", "trust0"))
        self.label_mintrust.setText(_translate("Dialog_fb_global", "mintrust"))
        self.lineEdit_adaptive_factor.setText(_translate("Dialog_fb_global", "0.2"))
        self.lineEdit_mintrust.setText(_translate("Dialog_fb_global", "0.00"))
        self.label_eig_lowerbound.setText(_translate("Dialog_fb_global", "eig_lowerbound"))
        self.lineEdit_eig_lowerbound.setText(_translate("Dialog_fb_global", "0.01"))
        self.groupBox.setTitle(_translate("Dialog_fb_global", "Regularization"))
        self.groupBox_priors.setTitle(_translate("Dialog_fb_global", "Priors(optional)"))
        self.label_BONDSB.setText(_translate("Dialog_fb_global", "BONDSB"))
        self.label_BONDSK.setText(_translate("Dialog_fb_global", "BONDSK"))
        self.label_ANGLESB.setText(_translate("Dialog_fb_global", "ANGLESB"))
        self.label_4.setText(_translate("Dialog_fb_global", "ANGLESK"))
        self.label_PDIHS3B.setText(_translate("Dialog_fb_global", "PDIHS3B"))
        self.label_PDIHS3K.setText(_translate("Dialog_fb_global", "PDIHS3K"))
        self.label_VDWS.setText(_translate("Dialog_fb_global", "VDWS"))
        self.label_VDWT.setText(_translate("Dialog_fb_global", "VDWT"))
        self.label_COUL.setText(_translate("Dialog_fb_global", "COUL"))
        self.groupBox_2.setTitle(_translate("Dialog_fb_global", "Settiing"))
        self.label_penalty_additive.setText(_translate("Dialog_fb_global", "penalty_additive"))
        self.label_normalize_weights.setText(_translate("Dialog_fb_global", "normalize_weights"))
        self.label_penalty_type.setText(_translate("Dialog_fb_global", "penalty_type"))
        self.comboBox_penalty_type.setItemText(0, _translate("Dialog_fb_global", "L2"))
        self.comboBox_penalty_type.setItemText(1, _translate("Dialog_fb_global", "L1"))
        self.lineEdit_penalty_additive.setText(_translate("Dialog_fb_global", "1"))
        self.lineEdit_normalize_weights.setText(_translate("Dialog_fb_global", "1"))
class Ui_Dialog_animate_vib(object):
    def setupUi(self, Dialog_animate_vib):
        Dialog_animate_vib.setObjectName("Dialog_animate_vib")
        Dialog_animate_vib.resize(562, 476)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog_animate_vib)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.webEngineView_vib = QtWebEngineWidgets.QWebEngineView(Dialog_animate_vib)
        self.webEngineView_vib.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_vib.setObjectName("webEngineView_vib")
        self.verticalLayout.addWidget(self.webEngineView_vib)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(280, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_prev = QtWidgets.QPushButton(Dialog_animate_vib)
        self.pushButton_prev.setObjectName("pushButton_prev")
        self.horizontalLayout.addWidget(self.pushButton_prev)
        self.pushButton_next = QtWidgets.QPushButton(Dialog_animate_vib)
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout.addWidget(self.pushButton_next)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.retranslateUi(Dialog_animate_vib)
    def retranslateUi(self, Dialog_animate_vib):
        _translate = QtCore.QCoreApplication.translate
        Dialog_animate_vib.setWindowTitle(_translate("Dialog_animate_vib", "Dialog"))
        self.pushButton_prev.setText(_translate("Dialog_animate_vib", "Prev"))
        self.pushButton_next.setText(_translate("Dialog_animate_vib", "Next"))
class Ui_Dialog_Denom(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Denom_Dialog")
        Dialog.resize(463, 299)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_optgeo_denom = QtWidgets.QGroupBox(Dialog)
        self.groupBox_optgeo_denom.setObjectName("groupBox_optgeo_denom")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_optgeo_denom)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_bond_denom = QtWidgets.QLabel(self.groupBox_optgeo_denom)
        self.label_bond_denom.setObjectName("label_bond_denom")
        self.gridLayout.addWidget(self.label_bond_denom, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_bond_denom = QtWidgets.QLineEdit(self.groupBox_optgeo_denom)
        self.lineEdit_bond_denom.setObjectName("lineEdit_bond_denom")
        self.gridLayout.addWidget(self.lineEdit_bond_denom, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_angle_denom = QtWidgets.QLabel(self.groupBox_optgeo_denom)
        self.label_angle_denom.setObjectName("label_angle_denom")
        self.gridLayout.addWidget(self.label_angle_denom, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_angle_denom = QtWidgets.QLineEdit(self.groupBox_optgeo_denom)
        self.lineEdit_angle_denom.setObjectName("lineEdit_angle_denom")
        self.gridLayout.addWidget(self.lineEdit_angle_denom, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_dihedral_denom = QtWidgets.QLabel(self.groupBox_optgeo_denom)
        self.label_dihedral_denom.setObjectName("label_dihedral_denom")
        self.gridLayout.addWidget(self.label_dihedral_denom, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_dihedral_denom = QtWidgets.QLineEdit(self.groupBox_optgeo_denom)
        self.lineEdit_dihedral_denom.setObjectName("lineEdit_dihedral_denom")
        self.gridLayout.addWidget(self.lineEdit_dihedral_denom, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_improper_denom = QtWidgets.QLabel(self.groupBox_optgeo_denom)
        self.label_improper_denom.setObjectName("label_improper_denom")
        self.gridLayout.addWidget(self.label_improper_denom, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_improper_denom = QtWidgets.QLineEdit(self.groupBox_optgeo_denom)
        self.lineEdit_improper_denom.setObjectName("lineEdit_improper_denom")
        self.gridLayout.addWidget(self.lineEdit_improper_denom, 1, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox_optgeo_denom)
        self.groupBox_liquid_denom = QtWidgets.QGroupBox(Dialog)
        self.groupBox_liquid_denom.setObjectName("groupBox_liquid_denom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_liquid_denom)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_rho_denom = QtWidgets.QLabel(self.groupBox_liquid_denom)
        self.label_rho_denom.setObjectName("label_rho_denom")
        self.gridLayout_2.addWidget(self.label_rho_denom, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_rho_denom = QtWidgets.QLineEdit(self.groupBox_liquid_denom)
        self.lineEdit_rho_denom.setObjectName("lineEdit_rho_denom")
        self.gridLayout_2.addWidget(self.lineEdit_rho_denom, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_liquid_denom)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_hvap_denom = QtWidgets.QLineEdit(self.groupBox_liquid_denom)
        self.lineEdit_hvap_denom.setObjectName("lineEdit_hvap_denom")
        self.gridLayout_2.addWidget(self.lineEdit_hvap_denom, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox_liquid_denom)
        self.retranslateUi(Dialog)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_optgeo_denom.setTitle(_translate("Dialog", "optgeo_denom"))
        self.label_bond_denom.setText(_translate("Dialog", "bond_denom"))
        self.lineEdit_bond_denom.setText(_translate("Dialog", "0.01"))
        self.label_angle_denom.setText(_translate("Dialog", "angle_denom"))
        self.lineEdit_angle_denom.setText(_translate("Dialog", "3"))
        self.label_dihedral_denom.setText(_translate("Dialog", "dihedral_denom"))
        self.lineEdit_dihedral_denom.setText(_translate("Dialog", "1000"))
        self.label_improper_denom.setText(_translate("Dialog", "improper_denom"))
        self.lineEdit_improper_denom.setText(_translate("Dialog", "1000"))
        self.groupBox_liquid_denom.setTitle(_translate("Dialog", "liquid_denom"))
        self.label_rho_denom.setText(_translate("Dialog", "rho_denom"))
        self.lineEdit_rho_denom.setText(_translate("Dialog", "7.8"))
        self.label_5.setText(_translate("Dialog", "hvap_denom"))
        self.lineEdit_hvap_denom.setText(_translate("Dialog", "0.3"))
class DenomSettingDialog(QtWidgets.QDialog, Ui_Dialog_Denom):
    def __init__(self, parent=None):
        super(DenomSettingDialog, self).__init__(parent)
        self.setupUi(self)
        self.setWindowTitle("Denom Setting")
class Ui_Dialog_packmol(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(511, 421)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(Dialog)
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView_packmol")
        self.horizontalLayout.addWidget(self.webEngineView)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog_packmol", "Dialog"))
class PackmolViewDialog(QtWidgets.QDialog, Ui_Dialog_packmol):
    def __init__(self, parent=None):
        super(PackmolViewDialog, self).__init__(parent)
        self.setupUi(self)
        self.setWindowTitle("Packmol Visualization")
class Psi4SettingDialog(QtWidgets.QDialog, Ui_Dialog_psi4_global_setting):
    def __init__(self, parent=None):
        super(Psi4SettingDialog, self).__init__(parent)
        self.setupUi(self)
        self.setWindowTitle("Psi4 Global Setting")
class FbSettingDialog(QtWidgets.QDialog, Ui_Dialog_fb_global):
    def __init__(self, parent=None):
        super(FbSettingDialog, self).__init__(parent)
        self.setupUi(self)
        self.setWindowTitle("Forcebalance Global Setting")
class VibAnimateDialog(QtWidgets.QDialog, Ui_Dialog_animate_vib):
    def __init__(self, parent=None):
        super(VibAnimateDialog, self).__init__(parent)
        self.setupUi(self)
        self.setWindowTitle("Vibration Animation")
class MyMainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(MyMainWindow, self).__init__(parent)
        self.setupUi(self)
        self.psi4_memory = "4"
        self.psi4_cpu = "4"
        self.fb_criteria = "1"
        self.fb_maxstep = "100"
        self.fb_convergence_gradient = "0.01"
        self.fb_convergence_objective = "0.01"
        self.fb_convergence_step = "0.01"
        self.fb_trust0 = "0.1"
        self.fb_mintrust = "0.00"
        self.fb_adaptive_damping = "1.0"
        self.fb_adaptive_factor = "0.2"
        self.fb_eig_lowerbound = "0.01"
        self.fb_penalty_additive = "1"
        self.fb_normalize_weights = "1"
        self.fb_penalty_type = "L2"
        self.denom_bond = "0.01"
        self.denom_angle = "3"
        self.denom_dihedral = "1000"
        self.denom_improper = "1000"
        self.denom_rho = "7.8"
        self.denom_hvap = "0.3"
        self.action_Psi4_global_Setting.triggered.connect(self.open_psi4_dialog)
        self.action_Forcebalance_global_Setting.triggered.connect(self.open_fb_dialog)
        self.pushButton_view_vibration.clicked.connect(self.open_vib_dialog)
        self.actionDenom_Setting.triggered.connect(self.open_denom_dialog)
    def open_psi4_dialog(self):
        dialog = Psi4SettingDialog(self)
        dialog.lineEdit_memory.setText(self.psi4_memory)
        dialog.lineEdit_cpu_number.setText(self.psi4_cpu)
        dialog.exec_()
        self.psi4_memory = dialog.lineEdit_memory.text().strip()
        self.psi4_cpu = dialog.lineEdit_cpu_number.text().strip()
    def open_fb_dialog(self):
        dialog = FbSettingDialog(self)
        dialog.lineEdit_criteria.setText(self.fb_criteria)
        dialog.lineEdit_maxstep.setText(self.fb_maxstep)
        dialog.lineEdit_convergence_gradient.setText(self.fb_convergence_gradient)
        dialog.lineEdit_convergence_objective.setText(self.fb_convergence_objective)
        dialog.lineEdit_convergence_step.setText(self.fb_convergence_step)
        dialog.lineEdit_trust0.setText(self.fb_trust0)
        dialog.lineEdit_mintrust.setText(self.fb_mintrust)
        dialog.lineEdit_adaptive_damping.setText(self.fb_adaptive_damping)
        dialog.lineEdit_adaptive_factor.setText(self.fb_adaptive_factor)
        dialog.lineEdit_eig_lowerbound.setText(self.fb_eig_lowerbound)
        dialog.lineEdit_penalty_additive.setText(self.fb_penalty_additive)
        dialog.lineEdit_normalize_weights.setText(self.fb_normalize_weights)
        dialog.exec_()
        self.fb_criteria = dialog.lineEdit_criteria.text().strip()
        self.fb_maxstep = dialog.lineEdit_maxstep.text().strip()
        self.fb_convergence_gradient = dialog.lineEdit_convergence_gradient.text().strip()
        self.fb_convergence_objective = dialog.lineEdit_convergence_objective.text().strip()
        self.fb_convergence_step = dialog.lineEdit_convergence_step.text().strip()
        self.fb_trust0 = dialog.lineEdit_trust0.text().strip()
        self.fb_mintrust = dialog.lineEdit_mintrust.text().strip()
        self.fb_adaptive_damping = dialog.lineEdit_adaptive_damping.text().strip()
        self.fb_adaptive_factor = dialog.lineEdit_adaptive_factor.text().strip()
        self.fb_eig_lowerbound = dialog.lineEdit_eig_lowerbound.text().strip()
        self.fb_penalty_additive = dialog.lineEdit_penalty_additive.text().strip()
        self.fb_normalize_weights = dialog.lineEdit_normalize_weights.text().strip()
        self.fb_penalty_type = dialog.comboBox_penalty_type.currentText().strip()
    def open_vib_dialog(self):
        dialog = VibAnimateDialog(self)
        dialog.exec_()
    def open_denom_dialog(self):
        dialog = DenomSettingDialog(self)
        dialog.lineEdit_bond_denom.setText(self.denom_bond)
        dialog.lineEdit_angle_denom.setText(self.denom_angle)
        dialog.lineEdit_dihedral_denom.setText(self.denom_dihedral)
        dialog.lineEdit_improper_denom.setText(self.denom_improper)
        dialog.lineEdit_rho_denom.setText(self.denom_rho)
        dialog.lineEdit_hvap_denom.setText(self.denom_hvap)
        result = dialog.exec_()
        self.denom_bond = dialog.lineEdit_bond_denom.text().strip()
        self.denom_angle = dialog.lineEdit_angle_denom.text().strip()
        self.denom_dihedral = dialog.lineEdit_dihedral_denom.text().strip()
        self.denom_improper = dialog.lineEdit_improper_denom.text().strip()
        self.denom_rho = dialog.lineEdit_rho_denom.text().strip()
        self.denom_hvap = dialog.lineEdit_hvap_denom.text().strip()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = MyMainWindow()
    main_window.show()
    sys.exit(app.exec_())
